ARG version
FROM almalinux:9
ENV course="devops" \
    trainer="jayanthi G" \
    duration="120hrs"
ARG USERNAME=jayanthi    
ARG USERNAME=$USERNAME
RUN echo "Hello User: ${USERNAME}", image version: ${version}" > /tmp/devops.txt
CMD ["sleep", "100"]   